{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from 整合版本1014 import main"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "\n",
    "def extract_categories(filename):\n",
    "    # 使用正则表达式匹配文件名格式\n",
    "    match = re.match(r'(\\d+-.+?) - (.+)', filename)\n",
    "    if match:\n",
    "        main_category = match.group(1).strip()\n",
    "        sub_category = match.group(2).strip()\n",
    "        return main_category, sub_category\n",
    "    else:\n",
    "        return None, None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：11955\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：11972\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：11987\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12003\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12019\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12036\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12053\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12071\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12088\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12104\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12121\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12137\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12153\n",
      "执行内存清理 - 批次 20\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12170\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12187\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12204\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12222\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12238\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12254\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12271\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12287\n",
      "执行内存清理 - 批次 30\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12303\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12320\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12336\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12352\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12367\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12383\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12400\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12417\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12434\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12451\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12468\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12485\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12502\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12518\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12535\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12552\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12568\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12584\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12601\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12618\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12635\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12651\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12667\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12683\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12701\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12718\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12735\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12752\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12769\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12785\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12801\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12818\n",
      "执行内存清理 - 批次 80\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12834\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12849\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12866\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12883\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12900\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12917\n",
      "执行内存清理 - 批次 90\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12935\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12952\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12969\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：12985\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13001\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13016\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13031\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13047\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13064\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13080\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13096\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13113\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13129\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13145\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13162\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13178\n",
      "执行内存清理 - 批次 110\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13195\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13211\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13228\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13245\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13263\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13280\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13295\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13311\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13327\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13342\n",
      "执行内存清理 - 批次 120\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13358\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13375\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13392\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13409\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13426\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13443\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13460\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13476\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13493\n",
      "执行内存清理 - 批次 130\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13509\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13526\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13542\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13558\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13574\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13591\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13607\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13624\n",
      "执行内存清理 - 批次 140\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13641\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13657\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13673\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13689\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13705\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13722\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13739\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13756\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13772\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13788\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13806\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13822\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13839\n",
      "执行内存清理 - 批次 160\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13855\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13872\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13887\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13903\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13920\n",
      "执行内存清理 - 批次 170\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13936\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13954\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13971\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：13988\n",
      "执行内存清理 - 批次 180\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14003\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14019\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14036\n",
      "执行内存清理 - 批次 190\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14053\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14069\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14086\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14102\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14119\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14136\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14153\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14169\n",
      "执行内存清理 - 批次 200\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14186\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14203\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14219\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14235\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14251\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14267\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14282\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14296\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14312\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14329\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14345\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14362\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14379\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14396\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14412\n",
      "Generated invalid data. Saved to 'invalid_outputs/6-软件与信息服务/软件外包及产业基地情况 (1).txt' for manual processing.\n",
      "发生错误：cannot access local variable 'generated_data' where it is not associated with a value。继续下一次生成。\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14429\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14445\n",
      "Generated valid data.\n",
      "已生成数据并追加到文件。当前总行数：14461\n"
     ]
    }
   ],
   "source": [
    "# 示例调用\n",
    "if __name__ == \"__main__\":\n",
    "    file_names = [\"6-软件与信息服务 - 软件外包及产业基地情况 (1)\", \"6-软件与信息服务 - 软件与信息技术服务商主要核心技术 (1)\", \"6-软件与信息服务 - 软件与信息技术服务商咨询与解决方案案例 (1)\", \"6-软件与信息服务 - 数字内容供应 (1)\", \"6-软件与信息服务 - MES应用信息 (1)\"] # 不需要带“.csv”后缀\n",
    "\n",
    "    for file_name in file_names:\n",
    "        main_category, sub_category = extract_categories(file_name)\n",
    "        file_path = f\"筛选出指定行之后的数据集/{main_category}/{file_name}.csv\"\n",
    "        save_path = f\"1029扩充后的数据集/{main_category}/{file_name}_expanded.csv\"\n",
    "        save_invalid_path = f\"invalid_outputs/{main_category}/{sub_category}.txt\"\n",
    "\n",
    "        num_entries = 20\n",
    "        custom_requirements = \"\"\n",
    "        required_total_rows = 20000\n",
    "\n",
    "        # 执行主流程\n",
    "        main(file_path, save_path, main_category, sub_category, num_entries, custom_requirements, required_total_rows, save_invalid_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
